version: "3.8"

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend

  frontend:
    build: ./gusaFront
    expose:
      - "3000"

volumes:
  h2_data:
